import math

from typing import TYPE_CHECKING

from .Primitive import Primitive

if TYPE_CHECKING:
    from .Mesh import Mesh


class Torus(Primitive):
    """Parameterized torus entity."""

    def __init__(self, name: str = None, radius: float = 1.0, tube: float = 0.25, 
                 radial_segments: int = 32, tubular_segments: int = 16, arc: float = math.pi * 2):
        """Constructor of Torus.
        
        Args:
            name: Name of the torus
            radius: Radius of the torus (distance from center to tube center)
            tube: Radius of the tube
            radial_segments: Number of radial segments
            tubular_segments: Number of tubular segments
            arc: Arc angle (default is 2*PI for a full torus)
        """
        if name is None:
            name = "Torus"
        super().__init__(name)
        self._radius = radius
        self._tube = tube
        self._radial_segments = radial_segments
        self._tubular_segments = tubular_segments
        self._arc = arc

    @property
    def radius(self) -> float:
        """Gets or sets the radius of the torus."""
        return self._radius

    @radius.setter
    def radius(self, value: float):
        """Sets the radius of the torus."""
        self._radius = value

    @property
    def tube(self) -> float:
        """Gets or sets the radius of the tube."""
        return self._tube

    @tube.setter
    def tube(self, value: float):
        """Sets the radius of the tube."""
        self._tube = value

    @property
    def radial_segments(self) -> int:
        """Gets or sets the radial segments."""
        return self._radial_segments

    @radial_segments.setter
    def radial_segments(self, value: int):
        """Sets the radial segments."""
        self._radial_segments = value

    @property
    def tubular_segments(self) -> int:
        """Gets or sets the tubular segments."""
        return self._tubular_segments

    @tubular_segments.setter
    def tubular_segments(self, value: int):
        """Sets the tubular segments."""
        self._tubular_segments = value

    @property
    def arc(self) -> float:
        """Gets or sets the arc angle."""
        return self._arc

    @arc.setter
    def arc(self, value: float):
        """Sets the arc angle."""
        self._arc = value

    def to_mesh(self) -> 'Mesh':
        """Convert current object to mesh."""
        from .Mesh import Mesh
        mesh = Mesh(self.name)
        
        radius = self._radius
        tube = self._tube
        arc = self._arc
        radial_segments = self._radial_segments
        tubular_segments = self._tubular_segments

        # Generate vertices for the torus
        # The torus is generated by sweeping a circle (tube) around an axis
        # u parameter: angle around the main circle (0 to arc)
        # v parameter: angle around the tube circle (0 to 2*PI)

        for i in range(radial_segments + 1):
            u = (i / radial_segments) * arc
            cos_u = math.cos(u)
            sin_u = math.sin(u)

            for j in range(tubular_segments + 1):
                v = (j / tubular_segments) * math.pi * 2
                cos_v = math.cos(v)
                sin_v = math.sin(v)

                # Torus parametric equation:
                # x = (R + r*cos(v)) * cos(u)
                # y = (R + r*cos(v)) * sin(u)
                # z = r * sin(v)
                x = (radius + tube * cos_v) * cos_u
                y = (radius + tube * cos_v) * sin_u
                z = tube * sin_v

                mesh.control_points.append((x, y, z, 1))

        # Create polygons connecting adjacent vertices
        for i in range(radial_segments):
            for j in range(tubular_segments):
                first = i * (tubular_segments + 1) + j
                second = first + tubular_segments + 1

                mesh.create_polygon([first, first + 1, second + 1, second])

        return mesh
